#!/usr/bin/python2

import fnmatch
import os
import sys
from subprocess import call
print("Generating hashes...")
for root, dirnames, filenames in os.walk('/home/mirror/linux'):
	for filename in fnmatch.filter(filenames, '*.tar.*'):
		if filename[-4:] == ".txt":
			continue
		p = os.path.join(root, filename)
		if os.path.islink(p):
			continue
		if not os.path.exists(p+".hash.txt"):
			sys.stdout.write('.')
			sys.stdout.flush()
			call("PATH=/bin/:/usr/bin echo sha256 $(sha256sum %s | cut -f1 -d' ') > %s.hash.txt" % ( p, p ), shell=True)
		else:
			sys.stdout.write('e')
			sys.stdout.flush()
print
print("Cleaning up old hashes...")
for root, dirnames, filenames in os.walk('/home/mirror/linux'):
	for filename in fnmatch.filter(filenames, '*.hash.txt'):
		p = os.path.join(root, filename)
		ptar = p[:-9]
		if not os.path.exists(ptar):
			os.unlink(p)
			sys.stdout.write('.')
			sys.stdout.flush()

print
print("Done!")
